### PR TITLE
Admin tidyup

### LINKED ISSUE #557: Login button doesn't work on mobile
Provide a general summary of the issue in the Title above

### Expected Behaviour
- If you're describing a bug, tell us what should happen
- If you're suggesting a change/improvement, tell us how it should work

### Current Behaviour
- If describing a bug, tell us what happens instead of the expected behavior
- If suggesting a change/improvement, explain the difference from current behavior

### Possible Solution
- Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change

### Steps to Reproduce (for bugs)
- Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant
1.
2.
3.
4.

### Tasks
Include specific tasks in the order they need to be done in.
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Remember to use helpful labels and milestones.

### PR DESCRIPTION
**Pull request by Br3nda**
Tidying up admin screens to match UI designs

closes #557

### CODE REVIEW

**Comment by Br3nda** [comment]
Note: The login button still doesn't work on mobile - you need to type then press enter.;
I'll fix that next.

File: app/controllers/admin/room_types_controller.rb [hunk 1]
```diff
@@ -1,19 +1,20 @@
 # frozen_string_literal: true
 
 class Admin::RoomTypesController < Admin::AdminController
+  respond_to :html
   before_action :set_room_type, only: %i[show edit update destroy]
 
   def index
     authorize :room_type
-    @room_types = policy_scope RoomType.all.order(:name)
+    @room_types = policy_scope(RoomType.all).order(:name)
```
Comment (jakerabid) [inline app/controllers/admin/room_types_controller.rb]: :+1: that was a subtle bug!
